hydra:
  run:
    dir: custom_outputs
  sweep:
    dir: concept_${num_concept}
    subdir: ${model_setting.model_name}/${knowledge_model_setting.model_name}



cwd: ???

process_uncompleted: False
do_eval_only: False
pred_file: ???

tiny_data: False
prompts_style: original
with_concepts: True
random_knowledge: False


#
model_setting:

  model_name: 
  batch_size: 128
  do_sample: True
  top_k: 10
  temperature: 0.1
  top_p: 0.95
  num_return_sequences: 1
  return_full_text: False
  max_length: 300

knowledge_model_setting:
  model_name: 
  batch_size: 32
  do_sample: True
  top_k: 10
  temperature: 0.1
  top_p: 0.95
  num_return_sequences: 1
  return_full_text: False
  max_length: 200



task: comve
gold_file: 
max_order: 4 #'Maximum n-gram order to use when computing BLEU score'
smooth: False # 'Whether or not to apply Lin et al. 2004 smoothing'



wandb_project_name: 
do_few_shot_learning: False


remove_punctuation: True

process_np: False
concept_model_name: FacebookAI/roberta-large
num_concept: 2
concepts_path: 


dataset: comve
data_path: 
output_path: results


